name: Pre-commit check

on:
  push:
    branches:
      - main
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
